<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Machine Learning - 2301CS621</b></center>

<center><b><h1>Lab - 7</b></center>
<pre>    

# Do all pre processing on diabetes csv

In [76]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
import matplotlib as plt
from sklearn.model_selection import KFold

In [26]:
data=pd.read_csv('/content/diabetes.csv')
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Import diabetes.csv data ser using sklearn

# Check the distribution of the target

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    object 
dtypes: float64(2), int64(6), object(1)
memory usage: 54.1+ KB


# Replace zeros with NaN for specific columns

In [28]:
data.replace(0, np.nan, inplace=True)

# Check for missing values

In [29]:
data.isnull().sum()

Pregnancies                 111
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [30]:
data['Pregnancies'] = data['Pregnancies'].fillna(data['Pregnancies'].median())
data['Glucose'] = data['Glucose'].fillna(data['Glucose'].median())
data['BloodPressure'] = data['BloodPressure'].fillna(data['BloodPressure'].median())
data['SkinThickness'] = data['SkinThickness'].fillna(data['SkinThickness'].median())
data['Insulin'] = data['Insulin'].fillna(data['Insulin'].median())
data['BMI'] = data['BMI'].fillna(data['BMI'].median())

# Convert Targer data into interger code

In [31]:
data['Outcome']=data['Outcome'].replace('Diabetic',1)
data['Outcome']=data['Outcome'].replace('Non Diabetic',0)

<ipython-input-31-3d47c1c19835>:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Outcome']=data['Outcome'].replace('Non Diabetic',0)


# Divide the data into input and output

In [32]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [33]:
x,y

(     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
 0            6.0    148.0           72.0           35.0    125.0  33.6   
 1            1.0     85.0           66.0           29.0    125.0  26.6   
 2            8.0    183.0           64.0           29.0    125.0  23.3   
 3            1.0     89.0           66.0           23.0     94.0  28.1   
 4            4.0    137.0           40.0           35.0    168.0  43.1   
 ..           ...      ...            ...            ...      ...   ...   
 763         10.0    101.0           76.0           48.0    180.0  32.9   
 764          2.0    122.0           70.0           27.0    125.0  36.8   
 765          5.0    121.0           72.0           23.0    112.0  26.2   
 766          1.0    126.0           60.0           29.0    125.0  30.1   
 767          1.0     93.0           70.0           31.0    125.0  30.4   
 
      DiabetesPedigreeFunction  Age  
 0                       0.627   50  
 1                    

# import KNN Model

In [44]:
from sklearn.neighbors import KNeighborsClassifier

# Convert all features into Z score

In [39]:
scaller=StandardScaler()
x_s=scaller.fit_transform(x)

In [105]:
x_s,len(x_s)


(array([[ 0.52939452,  0.86604475, -0.03198993, ...,  0.16661938,
          0.46849198,  1.4259954 ],
        [-1.14928009, -1.20506583, -0.5283186 , ..., -0.85219976,
         -0.36506078, -0.19067191],
        [ 1.20086436,  2.01666174, -0.69376149, ..., -1.33250021,
          0.60439732, -0.10558415],
        ...,
        [ 0.1936596 , -0.02157407, -0.03198993, ..., -0.910418  ,
         -0.68519336, -0.27575966],
        [-1.14928009,  0.14279979, -1.02464727, ..., -0.34279019,
         -0.37110101,  1.17073215],
        [-1.14928009, -0.94206766, -0.19743282, ..., -0.29912651,
         -0.47378505, -0.87137393]]),
 768)

# Splitting the dataset into the Training set and Test set

In [51]:
x_train,x_test,y_train,y_test=train_test_split(x_s,y,test_size=0.3,random_state=25)

# Create KNN Model

In [52]:
model=KNeighborsClassifier()

# Fitting KNN   on dataset

In [53]:
model.fit(x_train,y_train)

KNeighborsClassifier()

# Display classification_report

In [ ]:
KNeighborsClassifier(n_neighbors=20)

In [55]:
model.predict(x_test)

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1])

In [59]:
model.score(x_test,y_test)

0.7489177489177489

# Use Cross Validation to find best hyperparameter for KNN

In [60]:
print(classification_report(y_test,model.predict(x_test)))

              precision    recall  f1-score   support

           0       0.84      0.78      0.81       160
           1       0.58      0.68      0.62        71

    accuracy                           0.75       231
   macro avg       0.71      0.73      0.72       231
weighted avg       0.76      0.75      0.75       231



In [107]:
cross_val_score(KNeighborsClassifier(),x_train,y_train,cv=10)

array([0.77777778, 0.85185185, 0.72222222, 0.7037037 , 0.75925926,
       0.75925926, 0.62962963, 0.83018868, 0.77358491, 0.75471698])

# Extra: Use Pipline

In [108]:
pip=Pipeline([('scaler',StandardScaler()),('knn',KNeighborsClassifier())])

In [109]:
pip.fit(x_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

In [110]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=4)
for i, (train_index, test_index) in enumerate(kf.split(x)):
    print(f"Fold {i}:")
    print(f"  Training dataset index: {train_index}")
    print(f"  Test dataset index: {test_index}")

Fold 0:
  Training dataset index: [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
  Test dataset index: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
Fold 1:
  Training dataset index: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
  Test dataset index: [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]
Fold 2:
  Training dataset index: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
  Test d

In [116]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(KNeighborsClassifier(),{'n_neighbors':[5,10,15,20]},cv=10)
grid.fit(x_train,y_train)
grid.best_params_

{'n_neighbors': 15}